name: Football News Bot

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python main.py

      - name: Commit Updated File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add posted_articles.txt

          if ! git diff --staged --quiet; then
            git commit -m "Update posted articles"
            git pull --rebase origin main || true
            git push origin HEAD:main
          fi
